package common

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *CandleSeries) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Candles":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Candles")
				return
			}
			if cap(z.Candles) >= int(zb0002) {
				z.Candles = (z.Candles)[:zb0002]
			} else {
				z.Candles = make([]*Candle, zb0002)
			}
			for za0001 := range z.Candles {
				if dc.IsNil() {
					err = dc.ReadNil()
					if err != nil {
						err = msgp.WrapError(err, "Candles", za0001)
						return
					}
					z.Candles[za0001] = nil
				} else {
					if z.Candles[za0001] == nil {
						z.Candles[za0001] = new(Candle)
					}
					err = z.Candles[za0001].DecodeMsg(dc)
					if err != nil {
						err = msgp.WrapError(err, "Candles", za0001)
						return
					}
				}
			}
		case "MaxCount":
			z.MaxCount, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "MaxCount")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *CandleSeries) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "Candles"
	err = en.Append(0x82, 0xa7, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Candles)))
	if err != nil {
		err = msgp.WrapError(err, "Candles")
		return
	}
	for za0001 := range z.Candles {
		if z.Candles[za0001] == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = z.Candles[za0001].EncodeMsg(en)
			if err != nil {
				err = msgp.WrapError(err, "Candles", za0001)
				return
			}
		}
	}
	// write "MaxCount"
	err = en.Append(0xa8, 0x4d, 0x61, 0x78, 0x43, 0x6f, 0x75, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt(z.MaxCount)
	if err != nil {
		err = msgp.WrapError(err, "MaxCount")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *CandleSeries) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "Candles"
	o = append(o, 0x82, 0xa7, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Candles)))
	for za0001 := range z.Candles {
		if z.Candles[za0001] == nil {
			o = msgp.AppendNil(o)
		} else {
			o, err = z.Candles[za0001].MarshalMsg(o)
			if err != nil {
				err = msgp.WrapError(err, "Candles", za0001)
				return
			}
		}
	}
	// string "MaxCount"
	o = append(o, 0xa8, 0x4d, 0x61, 0x78, 0x43, 0x6f, 0x75, 0x6e, 0x74)
	o = msgp.AppendInt(o, z.MaxCount)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CandleSeries) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Candles":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Candles")
				return
			}
			if cap(z.Candles) >= int(zb0002) {
				z.Candles = (z.Candles)[:zb0002]
			} else {
				z.Candles = make([]*Candle, zb0002)
			}
			for za0001 := range z.Candles {
				if msgp.IsNil(bts) {
					bts, err = msgp.ReadNilBytes(bts)
					if err != nil {
						return
					}
					z.Candles[za0001] = nil
				} else {
					if z.Candles[za0001] == nil {
						z.Candles[za0001] = new(Candle)
					}
					bts, err = z.Candles[za0001].UnmarshalMsg(bts)
					if err != nil {
						err = msgp.WrapError(err, "Candles", za0001)
						return
					}
				}
			}
		case "MaxCount":
			z.MaxCount, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "MaxCount")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *CandleSeries) Msgsize() (s int) {
	s = 1 + 8 + msgp.ArrayHeaderSize
	for za0001 := range z.Candles {
		if z.Candles[za0001] == nil {
			s += msgp.NilSize
		} else {
			s += z.Candles[za0001].Msgsize()
		}
	}
	s += 9 + msgp.IntSize
	return
}
